### PR TITLE
docs: migrate wiki to gitbook

### LINKED ISSUE #51: Create documentation site?
The repo wiki is not conducive to collaboration. Thoughts on moving the documentation to a github pages site?

### PR DESCRIPTION
**Pull request by AndersDJohnson**
This migrates wiki documentation into a GitBook. It's in a sub-directory with its own `package.json` for future monorepo setup. A follow up PR will introduce a mechanism to publish. Then we can update README links and decommission the wiki.

A cool thing I learned that made this much easier than otherwise: you can grab the Markdown files and sidebar content from any GitHub wiki by cloning a secret repo with a `.wiki` suffix, e.g., `git clone git@github.com:ryanricard/mockyeah.wiki.git`.

Fixes #51, #70.

### CODE REVIEW

**Comment by AndersDJohnson** [comment]
@ryanricard I can't setup publishing to GitHub pages myself without admin permissions. Up to you at this point.

**Comment by ryanricard** [comment]
It would be nice keep the url similar to the repo url, whatever that takes.

**Comment by ryanricard** [comment]
@AndersDJohnson your saying you can setup the site with your collaboration rights, correct

**Comment by AndersDJohnson** [comment]
@ryanricard I don't know if I can - you need to setup GitHub pages in the repo settings to use a `gh-pages` branch.

**Pull request merged**
