### PR TITLE
feat: support proxying full urls, optionally mocking

### PR DESCRIPTION
**Pull request by AndersDJohnson**
Adds support for proxying any path to mockyeah URL that looks like an absolute URL to the actual backend via `http-proxy-middleware` (see below for choice rationale). Any URL can be optionally mocked as a path to prevent a trip to backend for it, while still allowing the rest through. This allows for partial mocking of real backends, so you can point to mockyeah from a real application and get mocked responses for some requests, but don't have to mock out every possible URL for all APIs used by the app to get realistic behavior. Could come in handy for local development, regression testing, demos, etc. where backend APIs can't be relied on for consistent responses to cause specific application behaviors.

Proxying behavior is disabled by default, but explicitly enabled with `mockyeah.proxy()`, so as not to interfere with `mockyeah.record()` and `mockyeah.play()`. A tighter integration, and proxying by default, and from the CLI, may come in a future PR.

There might be a future use case for proxying to backend but partially mocking some responses with a custom transform function if they match a mocked path. We'll have to see how to integrate that with our proxy middleware - possibly via its `onProxyRes`, which might receive as an argument the same `res` object that's passed through our route middleware, where we could set setting the metadata for the transform) - or consider another solution at that time.

I decided to go with `http-proxy-middleware` for now, but could have considered `request` and it's streaming capabilities with server responses (which we already use as well for the recording feature) - I'm not sure which has a better story about capturing response data for persistence to file for later playback, and for future features like the transform capability discussed above, but I'm leaning toward `http-proxy-middleware`.

Includes changes from #57, as those were needed for this functionality.

Closes #57.

### CODE REVIEW

**Comment by ryanricard** [comment]
@AndersDJohnson, please resolve conflicts.

**Comment by AndersDJohnson** [comment]
@ryanricard Conflicts resolved.

**Comment by AndersDJohnson** [comment]
@ryanricard I think eventually the recording feature will fold into this via additional `http-proxy-middleware` integration (see its options such as `onProxyRes`). I don't know whether you'd prefer that much of a sweeping change in this PR or as a separate one to follow up.

**Comment by AndersDJohnson** [comment]
@ryanricard I have reflected on this, and I don't think it's a bad feature to introduce for now. We can provide a deeper integration and refactoring later. The only tight coupling to dependent consumers here is the new public API `mockyeah.proxy()`, which we can continue to support, even if eventually it becomes a no-op because it's enabled by default or via configuration.

**Comment by ryanricard** [comment]
You're right, it did only take 2 seconds ;) 👍

**Pull request merged**
